name: Discord Notify

# master ブランチに対する PR が merge された時のみ実行される
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  myjob:
    if: |
      github.repository == 'roratorio-hub/ratorio' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        
      - name: Discord Notice
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 本番環境の更新作業が開始されました
          nofail: true
          noprefix: true
          notimestamp: true
